[package]
name = "danda_sharp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.17.1"
strum_macros = "0.24"

[profile.dev]
opt-level = 0